enable: zookeeper
etcd:
  rootDirectory: nextim
  address: [ localhost:12379 ]
  username: ''
  password: ''
zookeeper:
  schema: nextim
  address: [ z-3.devim.xt28b0.c3.kafka.us-east-2.amazonaws.com:2181,z-1.devim.xt28b0.c3.kafka.us-east-2.amazonaws.com:2181,z-2.devim.xt28b0.c3.kafka.us-east-2.amazonaws.com:2181 ]
  username: ''
  password: ''